baseurl = "https://github.com/nyoppy/nyoppy.com.gi/"
languageCode = "ja"
title = "nyoppy.com"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/nyoppy.com\">nyoppy.com</a> 2016"
disqusShortname = "shortname"

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

canonifyurls = true
